### ISSUE TITLE
Missing capstone_helpers.h?

### ISSUE THREAD

**Issue by nathankidd** [riverar/mach2#31]
I'm trying to build and hit:
`
1>mach2\src\scanner.cpp(27,10): fatal error C1083: Cannot open include file: 'capstone_helpers.h': No such file or directory
`
This header reference was added in 85fadaa9708679c99859e34bc75e221a1cd640d2.  `git log -S` on this project and the capstone repository show no other hits.  Where should one get this header?  (Maybe on a local disk and not added to the repo?)

If I revert 85fadaa9708679c99859e34bc75e221a1cd640d2 (I don't need ARM support) the build works fine.

VS2019 Version 16.4.3, building from current HEAD 5a081b21ae139c5ed6ba71ae39a73564ec6b1490.

**Comment by riverar** [comment]
@nathankidd Just saw this, sorry! Will fix that now.
